version: "3.8"

services:
  oop-mysqldb:
    image: mysql:5.7
    platform: linux/x86_64
    container_name: oop-mysqldb
    restart: always
    healthcheck:
      test: "mysqladmin ping -h localhost -proot"
      timeout: 5s
      interval: 1m
      retries: 10
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: oopPortfolio

  oop-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: oop-phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: oop-mysqldb
      PMA_PORT: 3306
    depends_on:
      oop-mysqldb:
        condition: service_healthy

  # oop-springboot:
  #   build: ./BackendServices
  #   container_name: oop-springboot
  #   ports:
  #     - 8082:8082
  #   environment:
  #     SPRING_PROFILES_ACTIVE: "production"
  #   depends_on:
  #     - oop-mysqldb
